{% set name = "markdownify" %}
{% set version = "0.11.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 009b240e0c9f4c8eaf1d085625dcd4011e12f0f8cec55dedf9ea6f7655e49bfe

build:
  number: 0
  entry_points:
    - markdownify = markdownify.main:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - beautifulsoup4 >=4.9,<5
    - pip
    - python
    - six >=1.15,<2
  run:
    - beautifulsoup4 >=4.9,<5
    - python
    - six >=1.15,<2

test:
  imports:
    - markdownify
    - tests
  commands:
    - markdownify --help

about:
  home: "http://github.com/matthewwithanm/python-markdownify"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Convert HTML to markdown."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - yhori991
